-- BUSCAR POR PRODUTO DENTRO DA VENDA 
-- QUERY - SELECT - LEITURA 
SELECT ID_PRODUTO,PRECO_UNITARIO
FROM ITEM_VENDA 
WHERE ID_VENDA = 1 AND ID_PRODUTO =1;
-- PESQUISANDO POR NOME 
SELECT IV.PRECO_UNITARIO,NOME_PRODUTO
FROM ITEM_VENDA AS IV -- AS= APELIDO 
JOIN PRODUTO AS P ON IV.ID_PRODUTO = P.ID_PRODUTO -- JUNTAR 
WHERE IV.ID_VENDA = 2 AND P.NOME_PRODUTO LIKE'%QUEIJO%';

-- BUSCAND0 TODAS AS VENDAS DE UM CLIENTE 
SELECT *
FROM VENDA
JOIN VENDA AS P ON IV.ID_VENDA = P.ID_CLIENTE -- JUNTAR 
WHERE ID_CLIENTE =1;

-- BUSCAR PRODUTO MAIS VENDIDO 
SELECT P.NOME_PRODUTO, SUM(IV.QUANTIDADE_ITEM)AS TOTAL_VENDIDO
FROM ID_VENDA AS IV  
JOIN PRODUTO P ON P. ID_PRODUTO = IV.QUANTIDADE_ITEM 
GROUP BY P.NOME_PRODUTO;