USE SISTEMA;


INSERT INTO CLIENTE (NOME_CLIENTE, EMAIL_CLIENTE) 
VALUES 
('João Silva', 'joao.silva@email.com'),
('Maria Souza', 'maria.souza@email.com');

INSERT INTO PRODUTO (NOME_PRODUTO, PRECO_PRODUTO) 
VALUES 
('PÃO', 2.00),
('QUEIJO', 12.50);

INSERT INTO VENDA (DATA_VENDA, ID_CLIENTE) 
VALUES 
('2026-04-28', 1),
('2025-04-29', 2);

INSERT INTO ITEM_VENDA (ID_VENDA, ID_PRODUTO, QUANTIDADE_ITEM, PRECO_UNITARIO) 
VALUES 
(1, 1, 1, 2.00), 
(2, 2, 2, 12.50); 