CREATE DATABASE SISTEMA;

USE SISTEMA;

CREATE TABLE CLIENTE(
ID_CLIENTE INT primary key auto_increment,
NOME_CLIENTE varchar(100)not null,
EMAIL_CLIENTE varchar(30) not null unique
);

CREATE TABLE PRODUTO(
ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY, 
NOME_PRODUTO VARCHAR(100) NOT NULL,
PRECO_PRODUTO DECIMAL(5,2) NOT NULL 
);

CREATE TABLE VENDA(
ID_VENDA INT AUTO_INCREMENT PRIMARY KEY, 
DATA_VENDA DATE NOT NULL,
ID_CLIENTE INT,
FOREIGN KEY(ID_CLIENTE)
REFERENCES CLIENTE(ID_CLIENTE)
);

CREATE TABLE ITEM_VENDA(
ID_VENDA INT,
ID_PRODUTO INT,
QUANTIDADE_ITEM INT NOT NULL,
PRECO_UNITARIO decimal(5,2) NOT NULL,
PRIMARY KEY(ID_VENDA, ID_PRODUTO),
FOREIGN KEY(ID_VENDA) REFERENCES VENDA (ID_VENDA),
FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID_PRODUTO)
);
