create database CINEMA;
USE CINEMA;

create table CLIENTE(
ID_CLIENTE INT primary key auto_increment,
NOME_CLIENTE varchar(100)not null,
CPF_CLIENTE varchar(15) not null unique,
EMAIL_CLIENTE varchar(100) not null unique,
STATUS_CLIENTE enum('ATIVO','INATIVO')
);

create table CATEGORIA(
ID_CATEGORIA int primary key auto_increment,
DESCRICAO_CAT varchar(30) not null
);

create table FILME(
ID_FILME int primary key auto_increment,
NOME_FILME varchar (100) not null,
FAIXA_ETARIA int check(FAIXA_ETARIA>=0),
DURACAO_FILME int not null, -- EM MINUTOS 
STATUS_FILME ENUM('EM CARTAZ','FORA CARTAZ'),
ID_CATEGORIA INT NOT NULL, 
FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA)
);

CREATE TABLE SALA (
    ID_SALA INT PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO_SALA TEXT NOT NULL,
    TIPO_SALA ENUM('2D', '3D', 'IMAX') DEFAULT '2D',
    CAPACIDADE_SALA INT NOT NULL CHECK (CAPACIDADE_SALA > 0),
    VIP_SALA BOOLEAN DEFAULT FALSE
);

CREATE TABLE SESSAO (
    ID_SESSAO INT AUTO_INCREMENT PRIMARY KEY,
    DATA_HORA DATETIME NOT NULL default current_timestamp,
    ID_SALA INT NOT NULL,
    FOREIGN KEY (ID_SALA)
        REFERENCES SALA (ID_SALA),
    ID_FILME INT NOT NULL,
    FOREIGN KEY (ID_FILME)
        REFERENCES FILME (ID_FILME),
	UNIQUE(DATA_HORA,ID_SALA) -- EVITA CONFLITO NA MESMA SALA 
);

CREATE table TIPO_INGRESSO(
ID_TIPO_INGRESSO INT primarY KEY auto_increment,
DESCRICAO_INGRESSO varchar(50) NOT NULL, 
VALOR_INGRESSO decimal(5,2) NOT NULL CHECK(VALOR_INGRESSO>=0)
);

create table PEDIDO(
ID_PEDIDO INT PRIMARY KEY auto_increment,
DATA_HORA datetime default current_timestamp,
ID_CLIENTE INT,
STATUS_PEDIDO ENUM('ABERTO', 'PAGO', 'CANCELADO') default 'ABERTO',
foreign key(ID_CLIENTE) references CLIENTE(ID_CLIENTE)
);

CREATE table INGRESSO(
ID_INGRESSO  INT primary KEY auto_increment, 
ID_PEDIDO INT NOT NULL, 
ID_SESSAO INT NOT NULL, 
ID_TIPO_INGRESSO INT NOT NULL,
VALOR_PAGO decimal(5,2) NOT NULL,
STATUS_INGRESSO ENUM('RESERVADO', 'PAGO', 'CANCELADO') DEFAULT 'RESERVADO',
FOREIGN KEY(ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
FOREIGN KEY(ID_SESSAO) REFERENCES SESSAO(ID_SESSAO),
FOREIGN KEY(ID_TIPO_INGRESSO) REFERENCES TIPO_INGRESSO(ID_TIPO_INGRESSO)
); 